export enum HttpStatusCodes {
    HTTP_BAD_REQUEST = 400,
    HTTP_NOT_AUTHORIZED = 401,
    HTTP_ALREADY_EXISTED = 409,
    SUCCESS = 200,
    CREATED = 201,
    INTERNAL_SERVER_ERROR = 500,
    NOT_FOUND = 404,
}